name: study_hub
description: "A Flutter project for lecturer and student"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  google_sign_in: ^6.3.0
  firebase_storage: ^12.4.6
  provider: ^6.1.4
  file_picker: ^10.1.8
  crypto: ^3.0.6
  url_launcher: ^6.3.1
  googleapis: ^11.4.0
  googleapis_auth: ^1.4.1
  badges: ^3.0.0
  flutter_bloc: ^9.1.0
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  timeago: ^3.7.0
  equatable: ^2.0.7
  share_plus: ^11.0.0
  rxdart: ^0.28.0
  permission_handler: ^11.3.1
  flutter_webrtc: ^0.14.1
  uuid: ^4.1.0
  percent_indicator: ^4.2.5
  path_provider: ^2.1.1
  path: ^1.8.3
  camera: ^0.10.5+5
  video_player: ^2.8.2
  shared_preferences: ^2.3.2
  pdf: ^3.11.3
  printing: ^5.14.0
  open_file: ^3.5.10
  android_intent_plus: ^5.3.0
  google_generative_ai: ^0.4.3
  flutter_dotenv: ^5.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Abeezee
      fonts:
        - asset: assets/fonts/Abeezee-Regular.ttf
