name: study_hub
description: "A Flutter project for lecturer and student"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  google_sign_in: ^6.3.0
  firebase_storage: ^12.4.6
  provider: ^6.1.4
  file_picker: ^10.1.8
  crypto: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Abeezee
      fonts:
        - asset: assets/fonts/Abeezee-Regular.ttf
