// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaghs-jpt3F1IbY53b-23YRZz8tX0x3DI',
    appId: '1:79357900802:web:ac3448beab462768544f1b',
    messagingSenderId: '79357900802',
    projectId: 'studyhub-d0239',
    authDomain: 'studyhub-d0239.firebaseapp.com',
    storageBucket: 'studyhub-d0239.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPJ4wRTdrMh2uy_ygb7lOSqEckG3h3yvw',
    appId: '1:79357900802:android:3b249dd8f4bb4e2a544f1b',
    messagingSenderId: '79357900802',
    projectId: 'studyhub-d0239',
    storageBucket: 'studyhub-d0239.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsAh_7ro-gFR2MLG0TljplDKdkG4A-XMg',
    appId: '1:79357900802:ios:48912e5fbe4c68f0544f1b',
    messagingSenderId: '79357900802',
    projectId: 'studyhub-d0239',
    storageBucket: 'studyhub-d0239.firebasestorage.app',
    iosBundleId: 'my.tarc.edu.studyHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsAh_7ro-gFR2MLG0TljplDKdkG4A-XMg',
    appId: '1:79357900802:ios:48912e5fbe4c68f0544f1b',
    messagingSenderId: '79357900802',
    projectId: 'studyhub-d0239',
    storageBucket: 'studyhub-d0239.firebasestorage.app',
    iosBundleId: 'my.tarc.edu.studyHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaghs-jpt3F1IbY53b-23YRZz8tX0x3DI',
    appId: '1:79357900802:web:d1f12d6f60661ddc544f1b',
    messagingSenderId: '79357900802',
    projectId: 'studyhub-d0239',
    authDomain: 'studyhub-d0239.firebaseapp.com',
    storageBucket: 'studyhub-d0239.firebasestorage.app',
  );
}
